networks:
    mc-server:
        external: true

services:
    mcauth:
        container_name: mcauth

        image: git.lunarflame.dev/docker/apps/mcauth:latest
        restart: unless-stopped

        ports:
            - "8080:8080"
        networks:
            - mc-server

        environment:
            ADMIN_USERNAME: ${ADMIN_USERNAME}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            RCON_HOST: javamc
            # This must be the password from your existing minecraft RCON session.
            # Do not make a new password!
            RCON_PASSWORD: ${RCON_PASSWORD}
            SERVER_LINK: ${SERVER_LINK}

        volumes:
            - ../javamc/data:/app/data
