services:
    jellyfin:
        container_name: jellyfin
        restart: unless-stopped

        # From jellyfin/jellyfin:latest
        image: git.lunarflame.dev/docker/apps/jellyfin:latest

        ports:
            # Discovery Port for Network Devices
            - "7359:7359/udp"
            - "8003:8096"

        environment:
            - JELLYFIN_PublishedServerUrl=https://jellyfin.lunarflame.dev

        volumes:
            - ./config:/config
            - ./cache:/cache
            - type: bind
              source: ~/psx/necronomicon/jellyfin
              target: /media

