services:
    mc:
        image: itzg/minecraft-server:latest
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        volumes:
            - "./data:/data"
            - "./backups:/backups"
        environment:
            EULA: "TRUE"
            # Allocate 4 GB of computer memory at most
            MEMORY: "4096M"
            # Difficulty. 3 is "Hard"
            DIFFICULTY: "3"
            ENABLE_WHITELIST: "true"
            # World name
            LEVEL: "Bedrock_level_v2"

            ENABLE_AUTOPAUSE: "FALSE"
            BACKUP_INTERVAL: "24h"
            BACKUP_RETENTION: "7"
            BACKUP_METHOD: "tar"

            # Enable RCON, a CLI app for entering commands into the server
            ENABLE_RCON: "true"
            RCON_PASSWORD: ${RCON_PASSWD}

            CREATE_CONSOLE_IN_PIPE: "true"

        restart: unless-stopped
