services:
    microbin:
        container_name: microbin
        restart: unless-stopped

        # From danielszabo99/microbin:latest
        image: ${LF_GIT}/apps/microbin:latest

        ports:
            - 8004:8080

        environment:
            MICROBIN_PUBLIC_PATH: /
            MICROBIN_DATA_DIR: /app/pasta_data
            MICROBIN_AUTHENTICATION: true
            MICROBIN_ENABLE_LOGIN: true
            MICROBIN_ADMIN_USERNAME: ${ADMIN_USER}
            MICROBIN_ADMIN_PASSWORD: ${ADMIN_PASSWD}

        volumes:
            - ./data:/app/pasta_data
