services:
    minio:
        container_name: minio
        restart: unless-stopped

        # From minio/minio:latest
        image: ${LF_GIT}/apps/minio:latest

        ports:
            - 8012:9000 # API
            - 8011:9001 # Console UI

        environment:
            MINIO_ROOT_USER: ${ROOT_USERNAME}
            MINIO_ROOT_PASSWORD: ${ROOT_PASSWORD}
        command: server /data --console-address ":9001"

        volumes:
            - ~/psx/necronomicon/minio:/data
