services:
    wireguard:
        container_name: wireguard 
        restart: unless-stopped

        # From ghcr.io/wgdashboard/wgdashboard:latest
        image: git.lunarflame.dev/docker/apps/wgdashboard:latest

        ports:
            - "8002:10086"

        cap_add:
            - NET_ADMIN
            - "51820:51820/udp"

        volumes:
            - ./aconf:/etc/amnezia/amneziawg
            - ./conf:/etc/wireguard
            - ./data:/data

volumes:
    aconf:
    conf:
    data:
