services:
    suwayomi:
        container_name: suwayomi
        restart: unless-stopped

        # From ghcr.io/suwayomi/suwayomi-server:preview
        image: git.lunarflame.dev/docker/apps/suwayomi/server:preview

        ports:
            - "8005:5000"

        environment:
            - AUTH_MODE=ui_login
            - AUTH_USERNAME=${AUTH_USER}
            - AUTH_PASSWORD=${AUTH_PW}
            - TZ=${TZ}
            - FLARESOLVERR_ENABLED=true
            - FLARESOLVERR_URL=http://suwayomi-byparr:8191
            - BIND_PORT=5000
        volumes:
            - ~/psx/necronomicon/suwayomi:/home/suwayomi/.local/share/Tachidesk

    byparr:
        container_name: suwayomi-byparr
        restart: unless-stopped

        # From ghcr.io/thephaseless/byparr:latest
        image: git.lunarflame.dev/docker/apps/byparr:latest

        init: true
        environment:
            - TZ=${TZ}
