networks:
    web:
        external: true

services:
    app:
        # Use the github image if git.lunarflame.dev is down
        image: ghcr.io/phantomforce260/apps/nginx-proxy-manager:latest

        # image: git.lunarflame.dev/docker/apps/nginx-proxy-manager:latest
        container_name: nginx-pm
        restart: unless-stopped
        environment:
            TZ: "America/New_York"
        ports:
            - "80:80"
            - "81"
            - "443:443"
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
        networks:
            web:
                aliases:
                    - drive.lunarflame.dev
                    - office.lunarflame.dev
