networks:
    rheia:
        external: true

services:
    kyutai:
        container_name: kyutai
        restart: unless-stopped

        image: git.lunarflame.dev/docker/rheia/kyutai:latest

        ports:
            - "${KYUTAI_PORT}:${KYUTAI_PORT}"
        networks:
            - rheia

        environment:
            - HOST=0.0.0.0
            - PORT=${KYUTAI_PORT}
            - HF_HOME=/cache/huggingface
            - VOICE=${VOICE}
        env_file:
          - .env

        volumes:
            - ./hf_cache:/cache/huggingface
            - ./voices:/app/voices
