networks:
    mc-server:
        external: true

services:
    javamc:
        container_name: javamc
        restart: unless-stopped

        # From itzg/minecraft-server:latest
        image: git.lunarflame.dev/docker/apps/javamc-server:latest

        ports:
            - "25565:25565"
        networks:
            mc-server:

        environment:
            EULA: "TRUE"
            MEMORY: ${MEMORY}
            DIFFICULTY: ${DIFF}
            ENABLE_WHITELIST: true
            LEVEL: ${WORLD_NAME}
            ENABLE_RCON: true
            RCON_PASSWORD: ${RCON_PASSWD}
            CREATE_CONSOLE_IN_PIPE: true
        tty: true
        stdin_open: true

        volumes:
            - ./data:/data

    backup:
        container_name: javamc-backup
        restart: unless-stopped
        depends_on:
            - javamc

        # From itzg/mc-backup:latest
        image: git.lunarflame.dev/docker/apps/javamc-server/backup:latest

        networks:
            mc-server:

        environment:
            RCON_HOST: javamc
            RCON_PORT: 25575
            RCON_PASSWORD: ${RCON_PASSWD}

            BACKUP_CRON_EXPRESSION: "0 4 * * *"
            TZ: "America/New_York"
            BACKUP_METHOD: tar
            PRUNE_BACKUPS_DAYS: 7
            INITIAL_DELAY: 2m

        volumes:
            - ./data:/data:ro
            - ${BACKUP_DIR}:/backups
