services:
  db:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    group_add:
        - 1001
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      NEXTCLOUD_TRUSTED_DOMAINS: "drive.lunarflame.dev 192.168.1.10"
      NEXTCLOUD_PROXY: "true"
    volumes:
      # Nextcloud internal data/config
      - nextcloud_data:/var/www/html

      # Samba-backed data (host mounts)
      - /home/adrian/samba:/mnt/samba:rw
      - /media/adrian:/mnt/media:rw

volumes:
  db_data:
  nextcloud_data:
