networks:
    web:
        external: true

services:
    db:
        image: mariadb:10.11
        container_name: nextcloud-db
        restart: unless-stopped
        command: --transaction-isolation=READ-COMMITTED
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./mariadb:/var/lib/mysql
        networks:
            - web

    nextcloud:
        image: nextcloud:latest
        container_name: nextcloud
        hostname: nextcloud
        restart: unless-stopped
        networks:
            - web
        group_add:
            - 1001
        ports:
            - "80"
        depends_on:
            - db
        environment:
            MYSQL_HOST: db
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            NEXTCLOUD_TRUSTED_DOMAINS: "drive.lunarflame.dev nextcloud"
            NEXTCLOUD_PROXY: "true"
            PHP_OPCACHE_MEMORY_CONSUMPTION: 256
            PHP_OPCACHE_MAX_ACCELERATED_FILES: 100000
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            PHP_OPCACHE_REVALIDATE_FREQ: 60
            PHP_UPLOAD_LIMIT: 100G
            NEXTCLOUD_UPLOAD_LIMIT: 100G
            APACHE_BODY_LIMIT: 0
            PHP_MEMORY_LIMIT: 512M
            PHP_POST_MAX_SIZE: 100G
            PHP_MAX_EXECUTION_TIME: 3600
        volumes:
            # Nextcloud internal data/config
            - ./data:/var/www/html

            # Samba-backed data (host mounts)
            - /home/adrian/dockerfiles/samba:/mnt/samba:rw
            - /media/adrian:/mnt/media:rw

    collabora:
        image: collabora/code
        container_name: collabora
        hostname: collabora
        restart: unless-stopped
        cap_add:
            - MKNOD
        environment:
            - username=${CB_USER}
            - password=${CB_PASSWD}
            - domain=drive\.lunarflame\.dev
            - server_name=office.lunarflame.dev
            - aliasgroup1=https://drive\.lunarflame\.dev:443
            - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:storage.wopi.host[0]=nextcloud
        ports:
            - "9980"
        networks:
            - web

volumes:
    db_data:
    nextcloud_data:
