services:
    npm:
        container_name: nginx-pm
        restart: unless-stopped

        # Use the github image if git.lunarflame.dev is down
        #image: ghcr.io/phantomforce260/apps/nginx-proxy-manager:latest

        # From jc21/nginx-proxy-manager:latest
        image: ${LF_GIT}/apps/nginx-proxy-manager:latest

        dns:
            - ${DNS_SERVER}
        ports:
            - 80:80
            - 8002:81
            - 443:443

        environment:
            TZ: "America/New_York"

        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
