services:
    playit:
        container_name: playit

        image: ghcr.io/playit-cloud/playit-agent:0.16
        restart: unless-stopped

        network_mode: host

        environment:
            - SECRET_KEY=${SECRET_KEY}
