services:
    filebrowser:
        # From filebrowser/filebrowser
        image: git.lunarflame.dev/docker/apps/filebrowser:latest
        container_name: filebrowser
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${BROWSER_ROOT}:/srv
            - ./appdata/filebrowser:/database
            - ./appdata/filebrowser:/config
        restart: unless-stopped
