services:
    filebrowser:
        container_name: filebrowser
        restart: unless-stopped

        # From filebrowser/filebrowser
        image: git.lunarflame.dev/docker/apps/filebrowser:latest

        ports:
            - "8099:80"

        environment:
            - PUID=1000
            - PGID=1000

        volumes:
            - ${BROWSER_ROOT}:/srv
            - ./appdata/filebrowser:/database
            - ./appdata/filebrowser:/config
