services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
