services:
    vaultwarden:
        container_name: vaultwarden
        restart: unless-stopped

        # From vaultwarden/server:latest
        image: ${LF_GIT}/apps/vaultwarden/server:latest

        ports:
            - 8006:80

        environment:
            DOMAIN: "https://${DOMAIN}"
            ADMIN_TOKEN: ${ADMIN_TOKEN}
            SIGNUPS_ALLOWED: false

        volumes:
            - ./data:/data
