networks:
    gitea:
        external: false

services:
    server:
        container_name: gitea
        restart: unless-stopped
        depends_on:
            - db

        # Use the github image if git.lunarflame.dev is down
        #image: ghcr.io/phantomforce260/apps/gitea:1.25.2

        # From docker.gitea.com/gitea:1.25.2
        image: git.lunarflame.dev/docker/apps/gitea:1.25.2

        ports:
            - "3000:3000"
            - "2222:2222"
        networks:
            - gitea

        environment:
            - USER_UID=1000
            - USER_GID=1000
            - GITEA__packages__ENABLED=true
            - GITEA__packages__container__ENABLED=true
            - GITEA__database__DB_TYPE=mysql
            - GITEA__database__HOST=gitea-db:3306
            - GITEA__database__NAME=${GITEA_DB_NAME}
            - GITEA__database__USER=${GITEA_DB_USER}
            - GITEA__database__PASSWD=${GITEA_DB_PASSWD}
            - GITEA__server__ROOT_URL=https://${DOMAIN}
            - GITEA__server__DOMAIN=${DOMAIN}
            - GITEA__server__SSH_DOMAIN=${SSH_DOMAIN}
            - GITEA__service__DISABLE_REGISTRATION=true
            - GITEA__service__REQUIRE_SIGNIN_VIEW=true

        volumes:
            - ./data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    db:
        container_name: gitea-db
        restart: unless-stopped

        # Use the github image if git.lunarflame.dev is down
        # image: ghcr.io/phantomforce260/base/mysql:8

        # From docker.io/library/mysql:8
        image: git.lunarflame.dev/docker/base/mysql:8

        networks:
            - gitea

        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}

        volumes:
            - ./mysql:/var/lib/mysql
