networks:
    web:
        external: true

services:
    suwayomi:
        # From ghcr.io/suwayomi/suwayomi-server:preview
        image: git.lunarflame.dev/docker/apps/suwayomi/server:preview
        container_name: suwayomi
        environment:
            - AUTH_MODE=ui_login
            - AUTH_USERNAME=${AUTH_USER}
            - AUTH_PASSWORD=${AUTH_PW}
            - TZ=${TZ}
            - FLARESOLVERR_ENABLED=true
            - FLARESOLVERR_URL=http://byparr:8191
            - BIND_PORT=${PORT}
        volumes:
            - ~/psx/necronomicon/suwayomi:/home/suwayomi/.local/share/Tachidesk
        ports:
            - ${PORT}
        restart: unless-stopped
        networks:
            - web

    byparr:
        # From ghcr.io/thephaseless/byparr:latest
        image: git.lunarflame.dev/docker/apps/byparr:latest
        container_name: byparr
        init: true
        environment:
            - TZ=${TZ}
        restart: unless-stopped
