services:
    filebrowser-init:
        container_name: filebrowser-init
        restart: no

        # From alpine:latest
        image: ${LF_GIT}/linux/alpine:latest
        user: root
        command: >
            sh -c "
              mkdir -p /data/filebrowser &&
              chown -R 1000:1000 /data
            "
        volumes:
            - ./appdata:/data

    filebrowser:
        container_name: filebrowser
        restart: unless-stopped
        depends_on:
            filebrowser-init:
                condition: service_completed_successfully

        # From filebrowser/filebrowser:latest
        image: ${LF_GIT}/apps/filebrowser:latest

        ports:
            - 8099:80

        volumes:
            - ${BROWSER_ROOT}:/srv
            - ./appdata/filebrowser:/database
            - ./appdata/filebrowser:/config
