networks:
    rheia:
        external: true

services:
    embeddings:
        # From ghcr.io/ggml-org/llama.cpp:server
        image: ${LF_GIT}/apps/llama.cpp:server
        container_name: llama-embeddings
        restart: unless-stopped

        ports:
            - "${PORT}:${PORT}"
        networks:
            - rheia

        volumes:
            - ~/Models:/models

        command: >
            --model /models/${MODEL}/model.gguf
            --host 0.0.0.0
            --port ${PORT}
            --embedding
            --ctx-size ${CTX_SIZE}
            --threads ${THREADS}
