networks:
    mc-server:
        external: true

services:
    mc:
        # From itzg/minecraft-server:latest
        image: git.lunarflame.dev/docker/apps/javamc-server:latest
        container_name: javamc
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        volumes:
            - "./data:/data"
            - "${BACKUP_DIR}:/backups"
        networks:
            mc-server:
        environment:
            EULA: "TRUE"
            MEMORY: "4096M"
            DIFFICULTY: 3 # Hard
            ENABLE_WHITELIST: true
            LEVEL: ${WORLD_NAME}

            ENABLE_AUTOPAUSE: "FALSE"
            BACKUP_INTERVAL: "24h"
            BACKUP_RETENTION: "7"
            BACKUP_METHOD: "tar"

            ENABLE_RCON: true
            RCON_PASSWORD: ${RCON_PASSWD}
            CREATE_CONSOLE_IN_PIPE: true

        restart: unless-stopped
