networks:
    mc-server:
        external: true

services:
    javamc:
        # From itzg/minecraft-server:latest
        image: git.lunarflame.dev/docker/apps/javamc-server:latest
        container_name: javamc
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        volumes:
            - "./data:/data"
        networks:
            mc-server:
        environment:
            EULA: "TRUE"
            MEMORY: "4096M"
            DIFFICULTY: 3 # Hard
            ENABLE_WHITELIST: true
            LEVEL: ${WORLD_NAME}
            ENABLE_RCON: true
            RCON_PASSWORD: ${RCON_PASSWD}
            CREATE_CONSOLE_IN_PIPE: true

        restart: unless-stopped

    backup:
        # From itzg/mc-backup:latest
        image: git.lunarflame.dev/docker/apps/javamc-server/backup:latest
        container_name: javamc-backup
        networks:
            mc-server:
        depends_on:
            - javamc

        environment:
            RCON_HOST: javamc
            RCON_PORT: 25575
            RCON_PASSWORD: ${RCON_PASSWD}

            BACKUP_CRON_EXPRESSION: "0 4 * * *"
            TZ: "America/New_York"
            BACKUP_METHOD: tar
            PRUNE_BACKUPS_DAYS: 7
            INITIAL_DELAY: 2m
        volumes:
            - "./data:/data:ro"
            - "${BACKUP_DIR}:/backups"
        restart: unless-stopped
