services:
    portainer:
        # From portainer/portainer-ce:lts
        image: git.lunarflame.dev/docker/apps/portainer/ce:lts
        container_name: portainer
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        dns:
            - 192.168.1.6
        ports:
            - "8001:9000"
            - "8000:8000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data:/data
