services:
    lazydocker:
        # From lazyteam/lazydocker:latest
        image: ${LF_GIT}/bin/lazydocker:latest
        container_name: lazydocker
        stdin_open: true
        tty: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config:/.config/jesseduffield/lazydocker
