services:
    formrelay:
        image: ${LF_GIT}/apps/formrelay:latest
        container_name: formrelay
        restart: unless-stopped
        ports:
          - 8007:3000
        volumes:
          - ./data:/app/data
